# Generated by Django 3.0.8 on 2020-09-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200905_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typee',
            field=models.TextField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], default='S', max_length=50),
        ),
    ]
