# Generated by Django 3.0.8 on 2020-09-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='typee',
            field=models.TextField(blank=True, choices=[('T', 'Teacher'), ('S', 'Student')], default='S', max_length=50),
        ),
    ]
