# Generated by Django 3.0.8 on 2020-09-21 20:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0002_auto_20200922_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='classsj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 1, 34, 39, 251638))),
                ('clid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.classsm')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
