# Generated by Django 3.1.1 on 2020-09-23 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20200923_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 17, 21, 59, 288414)),
        ),
    ]
