# Generated by Django 3.1.1 on 2020-09-23 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20200923_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 17, 39, 34, 249168)),
        ),
        migrations.CreateModel(
            name='classwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.TextField()),
                ('wsub', models.FileField(upload_to='')),
                ('clid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.classsm')),
                ('wtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.work')),
            ],
        ),
    ]
