# Generated by Django 3.1.1 on 2020-09-23 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20200923_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 18, 21, 33, 208198)),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='wsub',
            field=models.FileField(null='True', upload_to=''),
        ),
    ]
