# Generated by Django 3.1.1 on 2020-09-26 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_auto_20200923_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classwork',
            name='wsub',
        ),
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 26, 14, 22, 57, 466132)),
        ),
    ]
