# Generated by Django 3.1.1 on 2020-10-03 06:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0010_auto_20200927_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 3, 11, 32, 29, 331201)),
        ),
        migrations.CreateModel(
            name='submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stext', models.TextField()),
                ('sfile', models.FileField(null=True, upload_to='')),
                ('cwid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.classwork')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
