# Generated by Django 3.1.1 on 2020-10-04 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_auto_20201003_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 4, 13, 49, 47, 575417)),
        ),
    ]
