# Generated by Django 3.1.1 on 2020-10-04 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_auto_20201004_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 4, 19, 3, 36, 647996)),
        ),
    ]
