# Generated by Django 3.1.1 on 2020-10-04 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_auto_20201004_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 4, 19, 5, 19, 351739)),
        ),
    ]
