# Generated by Django 3.1.1 on 2020-10-04 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_auto_20201004_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='sub',
        ),
        migrations.AddField(
            model_name='qna',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 4, 19, 9, 10, 221826)),
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
