# Generated by Django 3.1.1 on 2020-10-05 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_auto_20201004_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='tid',
            new_name='sid',
        ),
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 16, 37, 47, 503732)),
        ),
    ]
