# Generated by Django 3.1.1 on 2020-10-05 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0018_auto_20201005_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 16, 38, 39, 957665)),
        ),
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 16, 38, 39, 942046)),
        ),
    ]
