# Generated by Django 3.1.1 on 2020-10-05 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0019_auto_20201005_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='qnas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 16, 49, 18, 759719))),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 16, 49, 18, 744058)),
        ),
        migrations.DeleteModel(
            name='qna',
        ),
    ]
