# Generated by Django 3.1.1 on 2020-10-06 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_auto_20201005_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 16, 42, 12, 397180)),
        ),
        migrations.AlterField(
            model_name='qnas',
            name='answer',
            field=models.TextField(default='No Answer Yet'),
        ),
        migrations.AlterField(
            model_name='qnas',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 16, 42, 12, 414496)),
        ),
    ]
