# Generated by Django 3.1.1 on 2020-10-06 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0021_auto_20201006_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 17, 47, 0, 820190)),
        ),
        migrations.AlterField(
            model_name='qnas',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 17, 47, 0, 835823)),
        ),
    ]
